[tool.pycln]
all = true

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = [
    "--numprocesses=auto",
    "--cov-report=term-missing",
    "--cov=src",
    "--no-cov-on-fail"
]
